timesformer:
  smqtk:
    class: TimesformerWithCharacterizationAdapter
    config:
      fe_params:
        model_name: vit_base_patch16_224
        num_classes: 29
        num_perspectives: 4
        num_locations: 2
        num_relations_with: 22
        num_relations_on: 13
        num_relations_what: 29
        arch: vit
        checkpoint_file_path: ${model_root}/checkpoint_epoch_00015.pyth
        num_gpus: 1
      kl_params:
        window_size: 100
        mu_train: 1.0
        sigma_train: 0.9798755511726752
        KL_threshold: 1.9159339787124976
        decay_rate: 0.6
        num_rounds: 40
        threshold_scale: 5.0
      evm_params:
        model_path: ${model_root}/timesformer_feats_evm.hdf5
        location_model_path: ${model_root}/timesformer_location_evm.hdf5
        perspective_model_path: ${model_root}/timesformer_perspective_evm.hdf5
        relation_on_model_path: ${model_root}/timesformer_relation_on_evm.hdf5
        relation_what_model_path: ${model_root}/timesformer_relation_what_evm.hdf5
        relation_with_model_path: ${model_root}/timesformer_relation_with_evm.hdf5
        distance_function: 'cosine'
        gpu_idx: 0
      characterization_params:
        min_novel_samples: 10
      dataloader_params:
        num_workers: 12
        pin_memory: True
        num_ensemble_views: 1
        num_spatial_crops: 3
        batch_size: 1
        n_threads: 0
        num_frames: 8
        sampling_rate: 32
        train_jitter_scales: [256, 320]
        test_crop_size: 224
        input_channel_num: [3]
      detection_threshold: 0.5
