defaults:
  - default
  - protocol/detection@protocol.smqtk.config: given
  - protocol/use_features@protocol.smqtk.config: consolidated
  - override /harness@protocol.smqtk.config.harness: par
  - protocol/feedback@protocol.smqtk.config: detection
  - _self_

server_url: ???
model_root: ???
protocol:
  smqtk:
    class: ONDProtocol
    config:
      domain: activity_recognition
      test_ids:
        - OND.10.90001.2100554
      dataset_root: ???
      feature_dir: ???
      harness:
        smqtk:
          class: ParHarness
          config:
            url: ${server_url}
            save_directory: ""
