defaults:
  - default
  - protocol/eval@protocol.smqtk.config: without_reaction
  - _self_

test_root: ???
model_root: ???
protocol:
  smqtk:
    class: ONDProtocol
    config:
      domain: activity_recognition
      test_ids:
        - OND.1.10001.6438158
      dataset_root: ???
      harness:
        smqtk:
          class: LocalHarness
          config:
            data_dir: ${test_root}/data
            result_dir: ${test_root}/results
            gt_dir: ${test_root}/data/OND/activity_recognition
            gt_config: ${test_root}/data/OND/activity_recognition/activity_recognition.json
